# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17j_fl6Sk3Tyd6e_MEOTad4GOYJ0ubaNE
"""

# app.py
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Configuración de la página
st.set_page_config(
    page_title="Dashboard Universitario",
    page_icon="🎓",
    layout="wide"
)

# Cargar datos
@st.cache_data
def load_data():
    data = {
        'Year': [2015, 2015, 2016, 2016, 2017, 2017, 2018, 2018, 2019, 2019,
                 2020, 2020, 2021, 2021, 2022, 2022, 2023, 2023, 2024, 2024],
        'Term': ['Spring', 'Fall'] * 10,
        'Applications': [2500, 2500, 2600, 2600, 2700, 2700, 2800, 2800,
                        3000, 3000, 2900, 2900, 3100, 3100, 3250, 3250,
                        3350, 3350, 3500, 3500],
        'Admitted': [1500, 1500, 1550, 1550, 1600, 1600, 1650, 1650,
                    1750, 1750, 1700, 1700, 1800, 1800, 1900, 1900,
                    2000, 2000, 2100, 2100],
        'Enrolled': [600, 600, 625, 625, 650, 650, 675, 675, 700, 700,
                    690, 690, 725, 725, 750, 750, 775, 775, 800, 800],
        'Retention Rate (%)': [85, 85, 86, 86, 87, 87, 86, 86, 88, 88,
                             85, 85, 87, 87, 88, 88, 89, 89, 90, 90],
        'Student Satisfaction (%)': [78, 78, 79, 79, 80, 80, 82, 82, 83, 83,
                                   81, 81, 84, 84, 85, 85, 86, 86, 88, 88],
        'Engineering Enrolled': [200, 200, 210, 210, 225, 225, 235, 235,
                               250, 250, 240, 240, 260, 260, 275, 275,
                               285, 285, 300, 300],
        'Business Enrolled': [150, 150, 160, 160, 165, 165, 175, 175,
                            185, 185, 180, 180, 195, 195, 200, 200,
                            210, 210, 225, 225],
        'Arts Enrolled': [125, 125, 130, 130, 135, 135, 140, 140, 145, 145,
                        140, 140, 150, 150, 160, 160, 165, 165, 175, 175],
        'Science Enrolled': [125, 125, 125, 125, 125, 125, 125, 125,
                           120, 120, 130, 130, 120, 120, 115, 115,
                           115, 115, 100, 100]
    }
    return pd.DataFrame(data)

# Cargar datos
df = load_data()
df['Admission Rate'] = (df['Admitted'] / df['Applications']) * 100

# Interfaz
st.title("🎓 Dashboard de Análisis Universitario")

# Filtros
col1, col2, col3 = st.columns(3)
with col1:
    año = st.selectbox("Año", ["Todos"] + sorted(df['Year'].unique()))
with col2:
    departamento = st.selectbox("Departamento", ["Todos", "Engineering", "Business", "Arts", "Science"])
with col3:
    semestre = st.selectbox("Semestre", ["Todos", "Spring", "Fall"])

# Aplicar filtros
df_filtrado = df.copy()
if año != "Todos":
    df_filtrado = df_filtrado[df_filtrado['Year'] == año]
if semestre != "Todos":
    df_filtrado = df_filtrado[df_filtrado['Term'] == semestre]

# KPIs
st.subheader("📊 Métricas Principales")
kpi1, kpi2, kpi3, kpi4 = st.columns(4)

with kpi1:
    st.metric("Solicitudes", f"{df_filtrado['Applications'].sum():,}")

with kpi2:
    tasa = df_filtrado['Admission Rate'].mean()
    st.metric("Tasa Admisión", f"{tasa:.1f}%")

with kpi3:
    ret = df_filtrado['Retention Rate (%)'].mean()
    st.metric("Retención", f"{ret:.1f}%")

with kpi4:
    sat = df_filtrado['Student Satisfaction (%)'].mean()
    st.metric("Satisfacción", f"{sat:.1f}%")

# Gráfico de tendencias
st.subheader("📈 Tendencias de Retención y Satisfacción")
tendencias = df.groupby('Year')[['Retention Rate (%)', 'Student Satisfaction (%)']].mean().reset_index()

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Scatter(x=tendencias['Year'], y=tendencias['Retention Rate (%)'],
                         name="Retención", line=dict(color='blue')), secondary_y=False)
fig.add_trace(go.Scatter(x=tendencias['Year'], y=tendencias['Student Satisfaction (%)'],
                         name="Satisfacción", line=dict(color='green')), secondary_y=True)

fig.update_layout(title="Evolución Anual", height=400)
fig.update_yaxes(title_text="Retención (%)", secondary_y=False)
fig.update_yaxes(title_text="Satisfacción (%)", secondary_y=True)

st.plotly_chart(fig, use_container_width=True)

# Distribución por departamento
st.subheader("🎯 Distribución por Departamento")

if departamento == "Todos":
    dept_data = {
        'Engineering': df_filtrado['Engineering Enrolled'].sum(),
        'Business': df_filtrado['Business Enrolled'].sum(),
        'Arts': df_filtrado['Arts Enrolled'].sum(),
        'Science': df_filtrado['Science Enrolled'].sum()
    }

    fig_pie = px.pie(values=list(dept_data.values()),
                     names=list(dept_data.keys()),
                     title="Matrícula por Departamento",
                     hole=0.3)
    st.plotly_chart(fig_pie, use_container_width=True)
else:
    dept_col = f'{departamento} Enrolled'
    dept_evol = df_filtrado.groupby('Year')[dept_col].mean().reset_index()

    fig_line = px.line(dept_evol, x='Year', y=dept_col,
                       title=f"Evolución de Matrícula - {departamento}",
                       markers=True)
    st.plotly_chart(fig_line, use_container_width=True)

# Comparación semestres
st.subheader("🔄 Comparación Spring vs Fall")
col1, col2 = st.columns(2)

with col1:
    fig_ret = px.line(df, x='Year', y='Retention Rate (%)', color='Term',
                     title='Retención por Semestre')
    st.plotly_chart(fig_ret, use_container_width=True)

with col2:
    fig_sat = px.line(df, x='Year', y='Student Satisfaction (%)', color='Term',
                     title='Satisfacción por Semestre')
    st.plotly_chart(fig_sat, use_container_width=True)

# Matriz de correlación
st.subheader("🔗 Correlación entre Variables")
variables_corr = ['Applications', 'Admitted', 'Enrolled', 'Retention Rate (%)',
                 'Student Satisfaction (%)', 'Engineering Enrolled',
                 'Business Enrolled', 'Arts Enrolled', 'Science Enrolled']

corr_matrix = df[variables_corr].corr()
fig_corr = px.imshow(corr_matrix, text_auto=True, aspect="auto",
                    color_continuous_scale='RdBu', title='Matriz de Correlación')
st.plotly_chart(fig_corr, use_container_width=True)

# Insights
st.subheader("💡 Recomendación Estratégica")
st.info("""
**Implementar programa de mentoría para estudiantes de Ciencias y Artes**

- **Justificación**: Estos departamentos muestran menor crecimiento en matrícula
- **Objetivo**: Mejorar retención y satisfacción estudiantil
- **Impacto esperado**: Incremento del 3-5% en tasas de persistencia
""")

st.success("✅ Dashboard implementado exitosamente en Streamlit Cloud")