# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17j_fl6Sk3Tyd6e_MEOTad4GOYJ0ubaNE
"""

# app.py
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Configuración de la página
st.set_page_config(
    page_title="Dashboard Universitario",
    page_icon="🎓",
    layout="wide"
)

# Cargar datos
@st.cache_data
def load_data():
    data = {
        'Year': [2015, 2015, 2016, 2016, 2017, 2017, 2018, 2018, 2019, 2019,
                 2020, 2020, 2021, 2021, 2022, 2022, 2023, 2023, 2024, 2024],
        'Term': ['Spring', 'Fall'] * 10,
        'Applications': [2500, 2500, 2600, 2600, 2700, 2700, 2800, 2800,
                        3000, 3000, 2900, 2900, 3100, 3100, 3250, 3250,
                        3350, 3350, 3500, 3500],
        'Admitted': [1500, 1500, 1550, 1550, 1600, 1600, 1650, 1650,
                    1750, 1750, 1700, 1700, 1800, 1800, 1900, 1900,
                    2000, 2000, 2100, 2100],
        'Enrolled': [600, 600, 625, 625, 650, 650, 675, 675, 700, 700,
                    690, 690, 725, 725, 750, 750, 775, 775, 800, 800],
        'Retention Rate (%)': [85, 85, 86, 86, 87, 87, 86, 86, 88, 88,
                             85, 85, 87, 87, 88, 88, 89, 89, 90, 90],
        'Student Satisfaction (%)': [78, 78, 79, 79, 80, 80, 82, 82, 83, 83,
                                   81, 81, 84, 84, 85, 85, 86, 86, 88, 88],
        'Engineering Enrolled': [200, 200, 210, 210, 225, 225, 235, 235,
                               250, 250, 240, 240, 260, 260, 275, 275,
                               285, 285, 300, 300],
        'Business Enrolled': [150, 150, 160, 160, 165, 165, 175, 175,
                            185, 185, 180, 180, 195, 195, 200, 200,
                            210, 210, 225, 225],
        'Arts Enrolled': [125, 125, 130, 130, 135, 135, 140, 140, 145, 145,
                        140, 140, 150, 150, 160, 160, 165, 165, 175, 175],
        'Science Enrolled': [125, 125, 125, 125, 125, 125, 125, 125,
                           120, 120, 130, 130, 120, 120, 115, 115,
                           115, 115, 100, 100]
    }
    return pd.DataFrame(data)

# Cargar datos
df = load_data()
df['Admission Rate'] = (df['Admitted'] / df['Applications']) * 100

# Interfaz
st.title("🎓 Dashboard de Análisis Universitario")

# Filtros
col1, col2, col3 = st.columns(3)
with col1:
    año = st.selectbox("Año", ["Todos"] + sorted(df['Year'].unique()))
with col2:
    departamento = st.selectbox("Departamento", ["Todos", "Engineering", "Business", "Arts", "Science"])
with col3:
    semestre = st.selectbox("Semestre", ["Todos", "Spring", "Fall"])

# Aplicar filtros
df_filtrado = df.copy()
if año != "Todos":
    df_filtrado = df_filtrado[df_filtrado['Year'] == año]
if semestre != "Todos":
    df_filtrado = df_filtrado[df_filtrado['Term'] == semestre]

# KPIs
st.subheader(" Métricas Principales")
kpi1, kpi2, kpi3, kpi4 = st.columns(4)

with kpi1:
    st.metric("Solicitudes", f"{df_filtrado['Applications'].sum():,}")

with kpi2:
    tasa = df_filtrado['Admission Rate'].mean()
    st.metric("Tasa Admisión", f"{tasa:.1f}%")

with kpi3:
    ret = df_filtrado['Retention Rate (%)'].mean()
    st.metric("Retención", f"{ret:.1f}%")

with kpi4:
    sat = df_filtrado['Student Satisfaction (%)'].mean()
    st.metric("Satisfacción", f"{sat:.1f}%")

# Gráfico de tendencias
st.subheader(" Tendencias de Retención y Satisfacción")
tendencias = df.groupby('Year')[['Retention Rate (%)', 'Student Satisfaction (%)']].mean().reset_index()

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Scatter(x=tendencias['Year'], y=tendencias['Retention Rate (%)'],
                         name="Retención", line=dict(color='blue')), secondary_y=False)
fig.add_trace(go.Scatter(x=tendencias['Year'], y=tendencias['Student Satisfaction (%)'],
                         name="Satisfacción", line=dict(color='green')), secondary_y=True)

fig.update_layout(title="Evolución Anual", height=400)
fig.update_yaxes(title_text="Retención (%)", secondary_y=False)
fig.update_yaxes(title_text="Satisfacción (%)", secondary_y=True)

st.plotly_chart(fig, use_container_width=True)

# Distribución por departamento
st.subheader(" Distribución por Departamento")

if departamento == "Todos":
    dept_data = {
        'Engineering': df_filtrado['Engineering Enrolled'].sum(),
        'Business': df_filtrado['Business Enrolled'].sum(),
        'Arts': df_filtrado['Arts Enrolled'].sum(),
        'Science': df_filtrado['Science Enrolled'].sum()
    }

    fig_pie = px.pie(values=list(dept_data.values()),
                     names=list(dept_data.keys()),
                     title="Matrícula por Departamento",
                     hole=0.3)
    st.plotly_chart(fig_pie, use_container_width=True)
else:
    dept_col = f'{departamento} Enrolled'
    dept_evol = df_filtrado.groupby('Year')[dept_col].mean().reset_index()

    fig_line = px.line(dept_evol, x='Year', y=dept_col,
                       title=f"Evolución de Matrícula - {departamento}",
                       markers=True)
    st.plotly_chart(fig_line, use_container_width=True)

# Comparación semestres
st.subheader(" Comparación Spring vs Fall")
col1, col2 = st.columns(2)

with col1:
    fig_ret = px.line(df, x='Year', y='Retention Rate (%)', color='Term',
                     title='Retención por Semestre')
    st.plotly_chart(fig_ret, use_container_width=True)

with col2:
    fig_sat = px.line(df, x='Year', y='Student Satisfaction (%)', color='Term',
                     title='Satisfacción por Semestre')
    st.plotly_chart(fig_sat, use_container_width=True)

# Insights
st.subheader(" Recomendación Estratégica")
st.info("""
**Implementar programa de mentoría para estudiantes de Ciencias y Artes**

- **Justificación**: Estos departamentos muestran menor crecimiento en matrícula
- **Objetivo**: Mejorar retención y satisfacción estudiantil
- **Impacto esperado**: Incremento del 3-5% en tasas de persistencia
""")

st.success(" Dashboard implementado exitosamente en Streamlit Cloud")

# Análisis Exploratorio de Datos Universitarios
import pandas as pd
import seaborn as sns
import numpy as np

# Configuración de estilo
plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

# Cargar datos
df = pd.read_csv('university_student_data.csv')

# Exploración inicial
print("INFORMACIÓN DEL DATASET")
print(f"Dimensiones: {df.shape}")
print("\nPrimeras filas:")
print(df.head())

print("\n ESTADÍSTICAS DESCRIPTIVAS ")
print(df.describe())

print("\n INFORMACIÓN DE COLUMNAS ")
print(df.info())

print("\n VALORES NULOS ")
print(df.isnull().sum())

# Documentación de columnas
columnas_contexto = {
    'Year': 'Año académico',
    'Term': 'Semestre (Spring/Fall)',
    'Applications': 'Número total de solicitudes de admisión',
    'Admitted': 'Número de estudiantes admitidos',
    'Enrolled': 'Número de estudiantes matriculados',
    'Retention Rate (%)': 'Tasa de retención estudiantil (%)',
    'Student Satisfaction (%)': 'Índice de satisfacción estudiantil (%)',
    'Engineering Enrolled': 'Estudiantes matriculados en Ingeniería',
    'Business Enrolled': 'Estudiantes matriculados en Negocios',
    'Arts Enrolled': 'Estudiantes matriculados en Artes',
    'Science Enrolled': 'Estudiantes matriculados en Ciencias'
}

print("\nSIGNIFICADO DE LAS COLUMNAS EN EL CONTEXTO DEL ESTUDIO ")
for col, significado in columnas_contexto.items():
    print(f"{col}: {significado}")

# 1. TENDENCIAS DE TASA DE RETENCIÓN A LO LARGO DEL TIEMPO
plt.figure(figsize=(12, 6))

# Promedio anual de retención
retencion_anual = df.groupby('Year')['Retention Rate (%)'].mean()

plt.subplot(1, 2, 1)
plt.plot(retencion_anual.index, retencion_anual.values, marker='o', linewidth=2, markersize=8)
plt.title('Tendencia de Tasa de Retención Anual', fontsize=14, fontweight='bold')
plt.xlabel('Año')
plt.ylabel('Tasa de Retención (%)')
plt.grid(True, alpha=0.3)

# Retención por semestre
plt.subplot(1, 2, 2)
sns.lineplot(data=df, x='Year', y='Retention Rate (%)', hue='Term', marker='o')
plt.title('Tasa de Retención por Semestre', fontsize=14, fontweight='bold')
plt.xlabel('Año')
plt.ylabel('Tasa de Retención (%)')
plt.legend(title='Semestre')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# 2. ÍNDICES DE SATISFACCIÓN ESTUDIANTIL POR AÑO
plt.figure(figsize=(12, 6))

# Satisfacción anual
satisfaccion_anual = df.groupby('Year')['Student Satisfaction (%)'].mean()

plt.subplot(1, 2, 1)
plt.bar(satisfaccion_anual.index, satisfaccion_anual.values, color='skyblue', alpha=0.7)
plt.title('Satisfacción Estudiantil por Año', fontsize=14, fontweight='bold')
plt.xlabel('Año')
plt.ylabel('Satisfacción (%)')
plt.xticks(rotation=45)

# Satisfacción por semestre
plt.subplot(1, 2, 2)
sns.boxplot(data=df, x='Term', y='Student Satisfaction (%)')
plt.title('Distribución de Satisfacción por Semestre', fontsize=14, fontweight='bold')
plt.xlabel('Semestre')
plt.ylabel('Satisfacción (%)')

plt.tight_layout()
plt.show()

# 3. COMPARACIÓN ENTRE SEMESTRES DE PRIMAVERA Y OTOÑO
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Aplicaciones por semestre
sns.barplot(data=df, x='Year', y='Applications', hue='Term', ax=axes[0,0])
axes[0,0].set_title('Solicitudes por Año y Semestre')
axes[0,0].tick_params(axis='x', rotation=45)

# Matriculados por semestre
sns.barplot(data=df, x='Year', y='Enrolled', hue='Term', ax=axes[0,1])
axes[0,1].set_title('Estudiantes Matriculados por Año y Semestre')
axes[0,1].tick_params(axis='x', rotation=45)

# Tasa de admisión por semestre
df['Admission Rate'] = (df['Admitted'] / df['Applications']) * 100
sns.lineplot(data=df, x='Year', y='Admission Rate', hue='Term', ax=axes[1,0], marker='o')
axes[1,0].set_title('Tasa de Admisión por Semestre')
axes[1,0].tick_params(axis='x', rotation=45)

# Distribución por departamentos
departamentos = ['Engineering Enrolled', 'Business Enrolled', 'Arts Enrolled', 'Science Enrolled']
df_departamentos = df.groupby('Term')[departamentos].mean()
df_departamentos.plot(kind='bar', ax=axes[1,1])
axes[1,1].set_title('Matrícula Promedio por Departamento y Semestre')
axes[1,1].tick_params(axis='x', rotation=0)

plt.tight_layout()
plt.show()

# 4. ANÁLISIS DE DEPARTAMENTOS
plt.figure(figsize=(14, 8))

# Evolución de matrícula por departamento
years = df['Year'].unique()
engineering = df.groupby('Year')['Engineering Enrolled'].mean()
business = df.groupby('Year')['Business Enrolled'].mean()
arts = df.groupby('Year')['Arts Enrolled'].mean()
science = df.groupby('Year')['Science Enrolled'].mean()

plt.subplot(2, 2, 1)
plt.plot(years, engineering, marker='o', label='Ingeniería')
plt.plot(years, business, marker='s', label='Negocios')
plt.plot(years, arts, marker='^', label='Artes')
plt.plot(years, science, marker='d', label='Ciencias')
plt.title('Evolución de Matrícula por Departamento', fontsize=14, fontweight='bold')
plt.xlabel('Año')
plt.ylabel('Estudiantes Matriculados')
plt.legend()
plt.grid(True, alpha=0.3)

# Distribución actual por departamentos
matricula_actual = df[df['Year'] == 2024][departamentos].mean()
plt.subplot(2, 2, 2)
plt.pie(matricula_actual.values, labels=[dept.replace(' Enrolled', '') for dept in departamentos],
        autopct='%1.1f%%', startangle=90)
plt.title('Distribución de Matrícula 2024 por Departamento')

# Correlación entre variables
plt.subplot(2, 2, 3)
correlation_matrix = df[['Applications', 'Admitted', 'Enrolled', 'Retention Rate (%)',
                        'Student Satisfaction (%)'] + departamentos].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0)
plt.title('Matriz de Correlación', fontsize=14, fontweight='bold')

# KPI principales
plt.subplot(2, 2, 4)
kpis = {
    'Tasa Admisión Prom': (df['Admitted'].sum() / df['Applications'].sum()) * 100,
    'Retención Prom': df['Retention Rate (%)'].mean(),
    'Satisfacción Prom': df['Student Satisfaction (%)'].mean(),
    'Crecimiento Matrícula': ((df[df['Year'] == 2024]['Enrolled'].mean() -
                              df[df['Year'] == 2015]['Enrolled'].mean()) /
                             df[df['Year'] == 2015]['Enrolled'].mean()) * 100
}

plt.bar(range(len(kpis)), list(kpis.values()), color=['blue', 'green', 'orange', 'red'])
plt.xticks(range(len(kpis)), list(kpis.keys()), rotation=45)
plt.title('Indicadores Clave de Rendimiento')
plt.ylabel('Porcentaje (%)')

for i, v in enumerate(kpis.values()):
    plt.text(i, v + 1, f'{v:.1f}%', ha='center', va='bottom')

plt.tight_layout()
plt.show()

# Hallazgos clave
print("\n RESULTADOS ")
print(f"1. La tasa de retención ha aumentado de {df[df['Year'] == 2015]['Retention Rate (%)'].mean():.1f}% a {df[df['Year'] == 2024]['Retention Rate (%)'].mean():.1f}%")
print(f"2. La satisfacción estudiantil creció de {df[df['Year'] == 2015]['Student Satisfaction (%)'].mean():.1f}% a {df[df['Year'] == 2024]['Student Satisfaction (%)'].mean():.1f}%")
print(f"3. Ingeniería es el departamento con mayor crecimiento: +{engineering.iloc[-1] - engineering.iloc[0]} estudiantes")
print(f"4. No hay diferencias significativas entre semestres Spring y Fall en los indicadores principales")